[project]
name = "design2code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.1",
    "numpy>=2.2.5",
    "setuptools>=80.1.0",
    "torch>=2.7.0",
    "tqdm>=4.67.1",
]
